import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "DriverLy",
    description: "Generated by DriverLy Team",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" foxified=""
            webcrx="">
            <AuthProvider>
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white `}
                >
                    {children}
                </body>
            </AuthProvider>
        </html>
    );
}
